### ISSUE TITLE
Database (structure) missing?

### ISSUE THREAD

**Issue by Gonomic** [reumerd/em-scan-beta#1]
Dennis, could you create a dump of the database (structure and data) and include that in this repo? I've got the server running, but no data. Furthermore is produces no questins to fill the DB myself.

**Comment by reumerd** [comment]
@Gonomic - Check Teams for a data example. For the datamodel itself it's shaped by api/models/Answers.js. No validation is yet included in the model. Its a JSON array of Name, Email and an Array of the Answers.
